name: 🐛 Bug Report
description: Report a bug in the RPG Engine v2.0
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please fill out the form below to help us understand and fix the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have read the documentation
          required: true
        - label: I can reproduce this bug consistently
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Engine Component
      description: Which part of the engine is affected?
      options:
        - AsyncGameEngine (Core engine)
        - ServiceContainer (Dependency injection)
        - EventBus (Event system)
        - UI System (Interactive interface)
        - Threading/Async (Cross-thread communication)
        - Demo Applications
        - Documentation
        - Other/Unknown
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened and what you expected to happen
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Run `python engine_demo.py`
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error messages or logs
      render: text

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      options:
        - "3.11"
        - "3.12"
        - "3.10"
        - "Other (specify in additional context)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 11
        - Windows 10
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or relevant information about the problem
