name: ✨ Feature Request
description: Suggest a new feature for the RPG Engine v2.0
title: "[Feature]: "
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Your ideas help make the RPG Engine better.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have reviewed the current roadmap
          required: true
        - label: This feature aligns with the async-first architecture
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - Core Engine (AsyncGameEngine)
        - Service Container (Dependency injection)
        - Event System (EventBus)
        - UI System (Interface improvements)
        - Game Systems (Character, Combat, etc.)
        - Developer Tools
        - Performance Optimization
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - Low (Nice to have)
        - Medium (Would improve workflow)
        - High (Essential for project goals)
        - Critical (Blocking other development)
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Brief one-line summary of the feature
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the current limitation or issue this feature addresses
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution
      placeholder: How would you like this feature to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: What other solutions have you considered?

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: Do you have ideas about how this could be implemented?
      placeholder: Technical details, API design, or architectural considerations

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        1. When developing a turn-based RPG...
        2. When integrating with external systems...
        3. When debugging performance issues...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to work on this feature
        - label: I can provide technical guidance
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references that would be helpful
