name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ "*" ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]  # test against multiple Python versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt   # include pytest, flake8, mypy, coverage, etc.

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Type-check with mypy
        run: |
          mypy .   # use . for the current directory

      - name: Run tests with coverage
        run: |
          pytest --maxfail=1 --disable-warnings --junitxml=junit/test-results.xml --cov=. --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true
