name: CI – Python

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Lint with flake8
        run: |
          # fail on syntax errors, warn on style issues
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Type-check with mypy
        run: |
          mypy .

      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings --junitxml=junit/test-results.xml
