name: Python Tests

on:
  push:
    branches: [ main, testing_center, develop, Test3 ]
  pull_request:
    branches: [ main, testing_center, develop, Test3 ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-asyncio
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Test async engine core imports
      run: |
        # Test new async engine imports
        python -c "import rpg_engine; print('✅ Main engine package imports successfully')"
        python -c "from rpg_engine.core.engine import AsyncGameEngine; print('✅ Async game engine imports successfully')" 
        python -c "from rpg_engine.core.service_container import ServiceContainer; print('✅ Service container imports successfully')"
        python -c "from rpg_engine.core.event_bus import EventBus; print('✅ Event bus imports successfully')"
        python -c "from rpg_engine.ui.ui_system import AsyncUIManager; print('✅ UI system imports successfully')"
        
    - name: Run async engine initialization tests
      run: |
        python -c "
        import asyncio
        from rpg_engine.core.service_container import ServiceContainer
        from rpg_engine.core.event_bus import EventBus
        from rpg_engine.core.engine import AsyncGameEngine
        
        async def test_engine():
            container = ServiceContainer()
            event_bus = EventBus()
            await container.register_singleton(EventBus, event_bus)
            engine = AsyncGameEngine(container)
            await engine.initialize_async()
            print('✅ Async engine initialization test passed')
            await engine.shutdown_async()
        
        asyncio.run(test_engine())
        "
        
    - name: Run service container tests
      run: |
        python -c "
        from game_sys.character.character_factory import create_character
        hero = create_character('hero')
        assert hero is not None
        assert hero.name == 'Valiant Hero'
        assert hasattr(hero, 'level')
        assert hasattr(hero, 'current_health')
        print('✅ Character creation tests passed')
        "
        
    - name: Run combat system tests
      run: |
        python -c "
        from game_sys.combat.combat_service import CombatService
        from game_sys.character.character_factory import create_character
        service = CombatService()
        hero = create_character('hero')
        enemy = create_character('goblin')
        assert service is not None
        assert hero is not None
        assert enemy is not None
        print('✅ Combat system tests passed')
        "
        
    - name: Run spell system tests
      run: |
        python -c "
        from game_sys.magic.spell_system import SpellSystem
        system = SpellSystem()
        assert system is not None
        spells = system.list_spells()
        assert isinstance(spells, list)
        print('✅ Spell system tests passed')
        "
        
    - name: Run item system tests  
      run: |
        python -c "
        from game_sys.items.item_factory import create_item
        sword = create_item('iron_sword')
        assert sword is not None
        assert hasattr(sword, 'name')
        print('✅ Item system tests passed')
        "

    - name: Run integration tests (if available)
      run: |
        if [ -f test_comprehensive.py ]; then
          python test_comprehensive.py
          echo '✅ Integration tests passed'
        else
          echo '⚠️ No integration tests found, skipping'
        fi
