name: CI – Python (Conda)

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: base
          environment-file: environment.yml

      - name: Install dev dependencies
        run: |
          conda install flake8 pytest mypy

      - name: Lint with flake8
        run: |
          # fail on errors, warn on style
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Type-check with mypy
        run: |
          mypy .

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings --junitxml=junit/test-results.xml
